const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const title = $('#pageTitle');
const pageNames = { chats: 'Добрый вечер, Алекс', anonymous: 'Анонимно', gifts: 'Магазин подарков', profile: 'Профиль', creator: 'Панель создателя' };
const toast = $('.toast');
let toastTimer;
function show(message) { clearTimeout(toastTimer); toast.textContent = message; toast.classList.add('show'); toastTimer = setTimeout(() => toast.classList.remove('show'), 2800); }
function openPage(name) { $$('.page').forEach(page => page.classList.toggle('active-page', page.id === name)); $$('.nav-item[data-page]').forEach(item => item.classList.toggle('active', item.dataset.page === name)); title.textContent = pageNames[name]; }
function modal({ title: heading, body, confirm = 'Продолжить', onConfirm }) {
  const element = document.createElement('div'); element.className = 'modal-backdrop';
  element.innerHTML = `<section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close" aria-label="Close">×</button><h2 id="modal-title">${heading}</h2><div class="modal-body">${body}</div><footer><button class="modal-cancel">Cancel</button><button class="modal-confirm">${confirm}</button></footer></section>`;
  const close = () => element.remove(); element.addEventListener('click', e => { if (e.target === element || e.target.closest('.modal-close, .modal-cancel')) close(); });
  $('.modal-confirm', element).addEventListener('click', () => { onConfirm?.(element); close(); }); document.body.append(element); $('.modal-close', element).focus();
}
$$('.nav-item[data-page]').forEach(button => button.addEventListener('click', () => openPage(button.dataset.page)));
$('#privacyButton').addEventListener('click', event => { event.currentTarget.classList.toggle('enabled'); const enabled = event.currentTarget.classList.contains('enabled'); localStorage.setItem('voicecore.streamerMode', String(enabled)); show(enabled ? 'Режим стримера включён только на этом устройстве.' : 'Режим стримера выключен.'); });
if (localStorage.getItem('voicecore.streamerMode') === 'true') $('#privacyButton').classList.add('enabled');
$('#newChat').addEventListener('click', () => modal({ title: 'Начать защищённый чат', body: '<label>Username or User ID<input id="recipient" placeholder="@username or 1234567890" autofocus></label>', confirm: 'Создать чат', onConfirm: node => { const recipient = $('#recipient', node).value.trim(); show(recipient ? `Secure chat request created for ${recipient}.` : 'Сначала укажите username или User ID.'); } }));
$('#composer').addEventListener('submit', event => { event.preventDefault(); const input = $('input', event.currentTarget); const text = input.value.trim(); if (!text) return; const bubble = document.createElement('div'); bubble.className = 'bubble outgoing'; bubble.textContent = text; const time = document.createElement('time'); time.textContent = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) + ' ✓'; bubble.append(time); $('.messages').append(bubble); input.value = ''; show('Сообщение сохранено локально. Для доставки подключите Chat Service.'); });
$$('.chat-row').forEach(row => row.addEventListener('click', () => { $$('.chat-row').forEach(item => item.classList.remove('selected')); row.classList.add('selected'); const name = $('strong', row).childNodes[0].textContent.trim(); $('.conversation header strong').childNodes[0].nodeValue = name + ' '; show(`Opened conversation with ${name}.`); }));
function transfer() { modal({ title: 'Перевести VH Coins', body: '<label>Recipient username or User ID<input id="transfer-user" placeholder="@username"></label><label>Amount in VH<input id="transfer-amount" inputmode="numeric" type="number" min="1" placeholder="100"></label><p class="form-note">The configured platform fee is calculated server-side when Wallet Service is connected.</p>', confirm: 'Проверить перевод', onConfirm: node => { const amount = Number($('#transfer-amount', node).value); show(amount > 0 ? `Transfer draft for ${amount} VH created. Server authorization is required to complete it.` : 'Укажите сумму больше нуля.'); } }); }
function topUp() { modal({ title: 'Пополнить VH-кошелёк', body: '<label>Choose a package<select id="package"><option>100 VH</option><option>500 VH</option><option>1,000 VH</option><option>5,000 VH</option></select></label><p class="form-note">Payments are only confirmed by a verified server-side payment webhook.</p>', confirm: 'Перейти к оплате', onConfirm: node => show(`${$('#package', node).value} payment session needs a configured payment provider.`) }); }
function report() { modal({ title: 'Пожаловаться на разговор', body: '<label>Category<select><option>Harassment</option><option>Spam</option><option>Threats</option><option>NSFW</option><option>Scam</option><option>Other</option></select></label><label>What happened?<textarea placeholder="Add context for the moderation team"></textarea></label>', confirm: 'Отправить жалобу', onConfirm: () => show('Черновик жалобы сохранён. Для защищённой отправки подключите Report Service.') }); }
document.addEventListener('click', event => { const button = event.target.closest('button'); if (!button || button.closest('.modal') || button.matches('.nav-item, #newChat, #privacyButton, .chat-row')) return; const text = button.textContent.trim().toLowerCase(); if (text.includes('send')) return transfer(); if (text.includes('top up')) return topUp(); if (text.includes('report')) return report(); if (text.includes('find a partner')) return modal({ title: 'Анонимный подбор', body: '<label>Language<select><option>English</option><option>Русский</option></select></label><label>Interests<input placeholder="Gaming, Music, Technology"></label><p class="form-note">Matching only starts after age, block-list and safety checks on the server.</p>', confirm: 'Найти собеседника', onConfirm: () => show('Настройки подбора сохранены локально. Для безопасного поиска нужен Matchmaking Service.') }); if (text.includes('gift')) return modal({ title: 'Магазин подарков', body: '<div class="gift-options"><button data-gift="Heart">♥ Heart · 50 VH</button><button data-gift="Rose">✿ Rose · 100 VH</button><button data-gift="Diamond">◆ Diamond · 500 VH</button></div>', confirm: 'Закрыть' }); if (text.includes('profile')) return openPage('profile'); if (text.includes('dashboard')) return openPage('creator'); if (text.includes('premium')) return modal({ title: 'Core Premium', body: '<p>Premium is cosmetic and never grants administrative permissions.</p><label>Plan<select><option>Monthly</option><option>Yearly</option></select></label>', confirm: 'Выбрать тариф', onConfirm: () => show('Для покупки Premium нужны Wallet и Premium services.') }); if (button.matches('.conversation-actions button')) return text.includes('⌁') || text.includes('▣') ? show('Для звонков требуются авторизованный WebRTC signaling и SFU.') : show('Открыты настройки разговора.'); if (button.matches('.icon-button')) return show('Сервисы поиска и уведомлений пока не подключены.'); if (!button.matches('.send')) show('Этому действию требуется подключение production service.'); });
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./service-worker.js').catch(() => {}));

// Local API integration. The same shell runs as a PWA on static hosting and as a messenger when served by apps/api/server.py.
const API = localStorage.getItem('voicecore.api') || `${location.origin}/api/v1`;
const token = () => localStorage.getItem('voicecore.accessToken') || 'dev-alex-token';
async function api(path, options = {}) { const response = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token()}`, ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Ошибка соединения'); return data; }
async function loadRealChats() { try { const chats = await api('/chats'); if (!chats.length) return; const list = $('.chat-list'); list.innerHTML = chats.map((chat, index) => `<article class="chat-row ${index ? '' : 'selected'}" data-chat-id="${chat.id}"><div class="avatar grad-${index % 4 + 1}">${chat.title.slice(0,2).toUpperCase()}</div><div><strong>${chat.title}</strong><p>${chat.preview || 'Нет сообщений'}</p></div><time>${chat.last_at ? new Date(chat.last_at * 1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}) : ''}</time></article>`).join(''); $$('.chat-row', list).forEach(row => row.addEventListener('click', () => loadMessages(row.dataset.chatId))); await loadMessages(chats[0].id); } catch (_) { /* Static hosting remains usable without API. */ } }
async function loadMessages(id) { try { const messages = await api(`/chats/${id}/messages`); $('.messages').innerHTML = '<div class="day">СЕГОДНЯ</div>' + messages.map(message => `<div class="bubble ${message.senderId === '1000000001' ? 'outgoing' : 'incoming'}">${escapeHtml(message.body)}<time>${new Date(message.created_at * 1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''); $('#composer').dataset.chatId = id; } catch (error) { show(error.message); } }
function escapeHtml(text) { const node = document.createElement('span'); node.textContent = text; return node.innerHTML; }
$('#composer').addEventListener('submit', async event => { const chatId = event.currentTarget.dataset.chatId; const input = $('input', event.currentTarget); if (!chatId || !input.value.trim()) return; try { await api(`/chats/${chatId}/messages`, {method:'POST',body:JSON.stringify({body:input.value.trim()})}); input.value=''; await loadMessages(chatId); } catch (_) { /* Existing local message path handles static PWA preview. */ } });
loadRealChats();
