const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const toast=$('.toast'), title=$('#pageTitle'), modalRoot=$('#modalRoot');
const names={chats:'Good evening, Alex',anonymous:'Anonymous matching',wallet:'VH Wallet',gifts:'Gift store',profile:'Profile',creator:'Creator workspace'};
let toastTimer;
function show(m){clearTimeout(toastTimer);toast.textContent=m;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
function openPage(name){$$('.page').forEach(p=>p.classList.toggle('active-page',p.id===name));$$('.nav-item[data-page],.mobile-nav [data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===name));title.textContent=names[name]||name;history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'smooth'})}
function modal({heading,body,confirm='Continue',onConfirm=()=>{}}){const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML='<section class="modal" role="dialog" aria-modal="true"><button class="modal-close">×</button><h2>'+heading+'</h2><div class="modal-body">'+body+'</div><footer><button class="modal-cancel">Cancel</button><button class="modal-confirm">'+confirm+'</button></footer></section>';modalRoot.append(el);const close=()=>el.remove();$('.modal-close',el).onclick=close;$('.modal-cancel',el).onclick=close;el.addEventListener('click',e=>{if(e.target===el)close()});$('.modal-confirm',el).onclick=()=>{onConfirm(el);close()};setTimeout(()=>$('.modal-close',el)?.focus(),0)}
function applyTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('voicecore.theme',theme);$('#themeLabel').textContent=theme==='dark'?'Dark theme':'Light theme';$('#themeIcon').textContent=theme==='dark'?'☾':'☀'}
const saved=localStorage.getItem('voicecore.theme');applyTheme(saved||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));
$('#themeToggle').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
$('#privacyButton').onclick=e=>{e.currentTarget.classList.toggle('enabled');const on=e.currentTarget.classList.contains('enabled');localStorage.setItem('voicecore.streamerMode',on);show(on?'Streamer mode enabled.':'Streamer mode disabled.')};
if(localStorage.getItem('voicecore.streamerMode')==='true')$('#privacyButton').classList.add('enabled');
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.page)));
$$('[data-page-go]').forEach(b=>b.addEventListener('click',()=>openPage(b.dataset.pageGo)));
$('#newChat').onclick=()=>modal({heading:'Start a secure chat',body:'<label>Username or User ID<input id="recipient" placeholder="@username or 1234567890"></label><p class="form-note">A server-side permission check is required before delivery.</p>',confirm:'Create chat',onConfirm:n=>show($('#recipient',n).value.trim()?'Chat request created.':'Enter a username or User ID.')});
$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('mobile-open');
$('#searchButton').onclick=()=>modal({heading:'Search VoiceCore',body:'<label>Search chats, users or messages<input id="searchInput" placeholder="Try Maya, #campaign or message text"></label><div class="search-hints"><span>Recent: Maya Chen</span><span>VoiceCore updates</span><span>#campaign</span></div>',confirm:'Search',onConfirm:n=>show('Search query queued for Search Service: '+($('#searchInput',n).value.trim()||'empty'))});
$('#notifyButton').onclick=()=>modal({heading:'Notifications',body:'<div class="notice"><b>New gift</b><span>Maya sent you a Heart · 2m ago</span></div><div class="notice"><b>Privacy update</b><span>New streamer controls are available · 1h ago</span></div><div class="notice"><b>Creator review</b><span>Report #VC-1842 needs attention · 12m ago</span></div>',confirm:'Mark all read',onConfirm:()=>show('Notifications marked as read.')});
$$('.chat-row').forEach(row=>row.onclick=()=>{const name=row.dataset.name;$$('.chat-row').forEach(r=>r.classList.remove('selected'));row.classList.add('selected');$('#conversationName').innerHTML=name+' <span class="online-dot"></span>';show('Opened '+name+'.')});
$('#composer').onsubmit=e=>{e.preventDefault();const input=$('input',e.currentTarget),text=input.value.trim();if(!text)return;const b=document.createElement('div');b.className='bubble outgoing';b.textContent=text;const t=document.createElement('time');t.textContent=new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+' ✓';b.append(t);$('#messages').append(b);input.value='';show('Message queued for Chat Service.')};
function walletSend(){modal({heading:'Send VH Coins',body:'<label>Recipient<input id="transferUser" placeholder="@username"></label><label>Amount<input id="transferAmount" type="number" min="1" placeholder="100"></label><p class="form-note">Fees and authorization are calculated server-side.</p>',confirm:'Review transfer',onConfirm:n=>{const a=Number($('#transferAmount',n).value);show(a>0?'Transfer draft created for '+a+' VH.':'Enter an amount greater than zero.')}})}
function topup(pkg){modal({heading:'Top up VH wallet',body:'<label>Package<select id="topupPkg"><option>100 VH</option><option '+(pkg==='500'?'selected':'')+'>500 VH</option><option '+(pkg==='1000'?'selected':'')+'>1,000 VH</option><option '+(pkg==='5000'?'selected':'')+'>5,000 VH</option></select></label><p class="form-note">Payment confirmation must arrive through a verified provider webhook.</p>',confirm:'Continue to payment',onConfirm:n=>show($('#topupPkg',n).value+' checkout requires a configured payment provider.')})}
function gift(name,price){modal({heading:'Send '+name,body:'<label>Recipient<input id="giftRecipient" placeholder="@username"></label><p class="gift-confirm">◇ '+price+' VH · '+name+'</p>',confirm:'Send gift',onConfirm:n=>show($('#giftRecipient',n).value.trim()?name+' gift draft created.':'Choose a recipient.')})}
function report(){modal({heading:'Report content',body:'<label>Category<select><option>Harassment</option><option>Spam</option><option>Threats</option><option>NSFW</option><option>Scam</option><option>Other</option></select></label><label>Context<textarea placeholder="What happened?"></textarea></label>',confirm:'Submit report',onConfirm:()=>show('Report prepared for the moderation queue.'))}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.closest('.modal'))return;
if(b.dataset.action==='send')return walletSend();if(b.dataset.action==='topup')return topup();if(b.dataset.action==='premium')return modal({heading:'Core Premium',body:'<p>Unlock cosmetic themes, profile accents, badges and expanded personalization.</p><div class="premium-list"><span>✓ Premium themes</span><span>✓ Profile styling</span><span>✓ Exclusive badges</span><span>✓ No administrative permissions</span></div><label>Plan<select><option>Monthly</option><option>Yearly</option></select></label>',confirm:'Continue',onConfirm:()=>show('Premium checkout is ready for the Premium Service.')});
if(b.dataset.action==='match')return show('Match preferences saved. Matchmaking Service will apply age, block-list and safety checks.');
if(b.dataset.action==='receive')return modal({heading:'Receive VH Coins',body:'<div class="receive-code">VC-ALEX-2840</div><p class="form-note">Share this receive code only with someone you trust.</p>',confirm:'Copy code',onConfirm:()=>show('Receive code copied locally.')});
if(b.dataset.action==='edit-profile')return modal({heading:'Edit profile',body:'<label>Display name<input value="Alex Volkov"></label><label>Bio<textarea placeholder="Tell people a little about you"></textarea></label><label>Username<input value="@alexv"></label>',confirm:'Save profile',onConfirm:()=>show('Profile changes saved locally.')});
if(b.dataset.action==='privacy')return modal({heading:'Privacy controls',body:'<div class="privacy-list"><span>Profile discoverability <b>Limited</b></span><span>Date of birth <b>Private</b></span><span>Online status <b>Contacts</b></span><span>Anonymous matching <b>Allowed</b></span></div>',confirm:'Done'});
if(b.dataset.action==='blocked')return modal({heading:'Blocked users',body:'<div class="notice"><b>@nightowl</b><span>Blocked Sep 18</span></div><div class="notice"><b>@unknown_47</b><span>Blocked Sep 12</span></div>',confirm:'Done'});
if(b.dataset.action==='delete')return modal({heading:'Delete account',body:'<p>This permanently removes your account data according to the configured retention policy. Active financial or moderation records may be retained where required.</p><label>Type DELETE to continue<input id="deleteConfirm"></label>',confirm:'Delete account',onConfirm:n=>show($('#deleteConfirm',n).value==='DELETE'?'Deletion request created.':'Deletion cancelled — exact confirmation required.')});
if(b.dataset.action==='streamer')return $('#privacyButton').click();
if(b.dataset.action==='copy')return show('Referral code copied locally.');
if(b.dataset.action==='review')return report();
if(b.dataset.action==='audit')return modal({heading:'Audit log',body:'<div class="notice"><b>Role check</b><span>Creator permissions evaluated · 1m ago</span></div><div class="notice"><b>Report update</b><span>VC-1842 assigned · 12m ago</span></div>',confirm:'Close'});
if(b.dataset.action==='room')return show('Private room setup requires authenticated realtime signaling.');
if(b.dataset.action==='attach')return show('Attachment picker requires Storage Service.');
if(b.dataset.action==='emoji')return show('Emoji picker ready for the messaging client.');
if(b.dataset.action==='conversation-menu')return modal({heading:'Conversation',body:'<button class="menu-action" data-action="report">Report conversation</button><button class="menu-action">Mute notifications</button><button class="menu-action">Block user</button>',confirm:'Done'});
if(b.dataset.action==='report')return report();
if(b.dataset.action==='wallet-menu')return openPage('wallet');
if(b.dataset.action==='transactions')return show('Transaction export requires Wallet Service.');
if(b.dataset.action==='delete')return;
if(b.dataset.gift)return gift(b.dataset.gift,b.dataset.price);
if(b.dataset.package)return topup(b.dataset.package);
if(b.dataset.themeChoice)return applyTheme(b.dataset.themeChoice);
if(b.dataset.call)return show((b.dataset.call==='voice'?'Voice':'Video')+' call requires authenticated WebRTC signaling and an SFU.');
if(b.id==='accountMenu')return modal({heading:'Account',body:'<div class="notice"><b>Alex Volkov</b><span>@alexv · Creator</span></div><button class="menu-action">Security sessions</button><button class="menu-action">Sign out</button>',confirm:'Close'});
});
$$('[data-theme-choice]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.themeChoice));
if(location.hash&&names[location.hash.slice(1)])openPage(location.hash.slice(1));
